warningBox: {
  backgroundColor: '#FEF9E7',
  borderWidth: 1,
  borderColor: '#F9E79F',
  borderRadius: 10,
  padding: 12,
  marginBottom: 20,
  width: '100%',
  flexDirection: 'row',
  alignItems: 'flex-start',
  gap: 8,
},
warningText: {
  fontSize: 12,
  color: '#7D6608',
  lineHeight: 16,
  flex: 1,
},
connectHint: {
  fontSize: 12,
  color: '#B2BEC3',
  marginTop: 12,
  textAlign: 'center',
},